// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SaveAllTheTabs
{
    internal sealed partial class Vsix
    {
        public const string Id = "SaveAllTheTabs.a0217e5b-1dfa-4fa1-98aa-7550d6a32076";
        public const string Name = "Save All the Tabs";
        public const string Description = @"Quickly save and restore sets of document tabs.";
        public const string Language = "en-US";
        public const string Version = "1.1.0";
        public const string Author = "Eric Amodio";
        public const string Tags = "tabs,tab management,documents,document management";
    }
}
